### ISSUE TITLE
Scan shows an extension that is not installed

### ISSUE THREAD

**Issue by matteocontrini** [migratetoflarum/lab.migratetoflarum.com#6]
Hi,
when scanning my forum (https://forum.fibra.click), the website says that I'm using an extension called "Eve Login".

![Eve Login](https://user-images.githubusercontent.com/2164763/53808536-ca92d780-3f52-11e9-8a20-96102dd0a468.png)

I don't have that extension installed though, and I have never installed it (it's the first time I hear of it).

What is causing the detection of that extension? 🤔

**Comment by clarkwinkelmann** [comment]
The problem is that @instkffff forked the GitHub auth extension and many of the releases from his package include the same extension ID as GitHub Auth, so the lab cannot know which one it is. I could have blacklisted those versions but because it has so few downloads and many tags inherited from core it's easier for me to just block the extension completely.

The extension should now stop appearing in new scans.

I also blocked the eve bio extension from the same author that appears to be just a fork of the fof bio extension with shared tagged releases as well.

@instkffff if you read this and want your extension to appear in the lab again, the best would be unlink the fork from the original github extension and delete all the problematic tagged releases as well as those inherited from core, so only your own tags are published to packagist. Then ask me to remove the hidden flag on your extension :wink:
