### ISSUE TITLE
Issue: Is answering on multiple urls

### ISSUE THREAD

**Issue by PeopleInside** [migratetoflarum/lab.migratetoflarum.com#9]
Hi, i manage two flarum community.
One has score A+ and the second has score C
The message on the result's say:

Your forum is answering to multiple urls. Set redirects to a single canonical url. Assets won't load correctly on the non-canonical domains

I'm unable to find any issue, how to solve?

A+ https://community.peopleinside.it
C https://community.marcoborla.it

**Comment by clarkwinkelmann** [comment]
Hi. The problem is that you can access the second site from both https://community.marcoborla.it/ and https://www.community.marcoborla.it/

You should setup a www => no www redirect. The way to do it depends on the web server used. You should be able to re-use the same configuration from your other website.

Alternatively you can install the [canonical url](https://discuss.flarum.org/d/19307-canonical-url-redirect) extension that will take care of redirecting visitors to a single url.

If you need help setting up the redirect, feel free to ask on the Flarum community and include which web server you are using (Apache, Nginx, ...)

**Comment by PeopleInside** [comment]
@clarkwinkelmann thanks, with your explain is now solved.
